name: Deploy Telegram Bot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests (if any)
        run: npm test --if-present

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}

            # Останавливаем текущий процесс
            pm2 stop paintshop-bot || true

            # Обновляем код
            git pull origin main

            # Устанавливаем зависимости
            npm ci --production

            # Создаем .env если его нет
            if [ ! -f .env ]; then
              echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
              echo "NODE_ENV=production" >> .env
            fi

            # Запускаем бота
            pm2 start bot.js --name "paintshop-bot" --watch

            # Сохраняем конфигурацию PM2
            pm2 save
            pm2 startup || true

            echo "✅ Деплой завершен успешно!"
